name: Deploy to Vercel (prod)

on:
  push:
    branches:
      - main

jobs:
  deployVercel:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Link to Vercel Project
        run: npx vercel link --yes --scope=${{ secrets.VERCEL_ORG }} --token=${{ secrets.VERCEL_TOKEN }} --project=${{ secrets.VERCEL_PROJECT }}
        env:
          VERCEL_ORG: ${{ secrets.VERCEL_ORG }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT: ${{ secrets.VERCEL_PROJECT }}

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --scope=${{ secrets.VERCEL_ORG }} --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG: ${{ secrets.VERCEL_ORG }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}